#!/bin/bash 

rm halt_client.out
make halt_client.out

old_records=$(cat ../server/records.txt)
echo -e "file01 6 10" > ../server/records.txt
echo sleeping 6s to ./startserver
sleep 6

curl -s localhost:9087/file01 -o out_files/server_response1

./halt_client.out

diff1=$(diff out_files/proxy_response1 out_files/server_response1)
diff2=$(diff out_files/proxy_response2 out_files/server_response1)
diff3=$(diff out_files/proxy_response3 out_files/server_response1)

if [ "$diff1" != "" ]
then
	echo diff1 FAILED
else
	echo diff1 PASSED 
fi

if [ "$diff2" != "" ]
then
	echo diff2 FAILED
else
	echo diff2 PASSED 
fi

if [ "$diff3" != "" ]
then
	echo diff3 FAILED
else
	echo diff3 PASSED 
fi

echo -e "$old_records" > ../server/records.txt
echo reminder to shut server down
