#!/bin/bash

rm interleaved_clients.out
make interleaved_clients.out

./interleaved_clients.out

curl -s http://www.cs.tufts.edu/comp/112/index.html -o out_files/server_response1
curl -s http://www.cs.cmu.edu/~prs/bio.html -o out_files/server_response2 
curl -s http://www.testingmcafeesites.com/index.html -o out_files/server_response3
curl -s http://www.testingmcafeesites.com/testcat_ac.html -o out_files/server_response4

diff1=$(diff out_files/proxy_response1 out_files/server_response1)
diff2=$(diff out_files/proxy_response2 out_files/server_response2) 
diff3=$(diff out_files/proxy_response3 out_files/server_response3) 
diff4=$(diff out_files/proxy_response4 out_files/server_response4) 

if [ "$diff1" != "" ]
then
	echo diff1 FAILED
else
	echo diff1 PASSED 
fi

if [ "$diff2" != "" ] 
then
	echo diff2 FAILED
else
	echo diff2 PASSED
fi

if [ "$diff3" != "" ]
then
	echo diff3 FAILED
else
	echo diff3 PASSED 
fi

if [ "$diff4" != "" ] 
then
	echo diff4 FAILED
else
	echo diff4 PASSED
fi




