#!/bin/bash

# check that GET resets stale timer 
    # GET file 1 (suppose max-age = 10)
    # wait 5 seconds 
    # GET file 1
    # wait 7 seconds 
    # GET file 1 -> refetch
    # wait 7 seconds 
    # GET file 1 -> should hit cache with last put time update

old_records=$(cat ../server/records.txt)
echo -e "file01 6 10" > ../server/records.txt
echo sleeping 6s to ./startserver
sleep 6
curl -s -x localhost:9086 localhost:9087/file01 -o out_files/proxy_response
echo "Got first response!"
sleep 5 
curl -s -x localhost:9086 localhost:9087/file01 -o out_files/proxy_response
echo "Got second response!"
sleep 7
curl -s -x localhost:9086 localhost:9087/file01 -o out_files/proxy_response
echo "Got third response!"
sleep 7
curl -s -i -x localhost:9086 localhost:9087/file01 -o out_files/proxy_response
echo "Got fourth response!"
result=$(cat out_files/proxy_response | grep Age:)

if [ "$result" != "" ]
then
    echo PASSED 
else
    echo FAILED 
fi

echo -e "$old_records" > ../server/records.txt
echo reminder to shut server down